JamesThew/model/Controllers/ContestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using model;

namespace model.Controllers
{
    public class ContestsController : Controller
    {
        private DefaultConnectionEntities db = new DefaultConnectionEntities();

        // GET: Contests
        public ActionResult Index()
        {
            List<Contest> li;
            //var date = DateTime.Now.Date;
            ChangeStatus();
            if (!User.IsInRole("admin"))
            {
               li = db.Contests.Where(y => y.Status == "active").ToList();
            }
            else
            {
                li = db.Contests.Where(y => y.Status == "inactive").ToList();
            }
            return View(li);
        }
        
        public ActionResult IndexP(int? id)
        {
            //ViewBag.Contest = contest.Name;
            return RedirectToAction("CreateP", "Participants",new { Id=id});
            //return View("../Views/Participants/CreateP",new { Name=contest.Name});
        }

        // GET: Contests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.Contests.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // GET: Contests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contest contest, HttpPostedFileBase file)
        {
            var now = DateTime.Now.Date;
            if(contest.Ending_Date<now)
            {
                contest.Status = "inactive";

            }
            else
            {
                contest.Status = "active";
            }
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    
                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Content/images/" + ImageName);

                    // save image in folder
                    file.SaveAs(physicalPath);

                }

                db.Contests.Add(contest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contest);
        }

        // GET: Contests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.Contests.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // POST: Contests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Image,Name,Description,Starting_Date,Ending_Date,Winner_Id")] Contest contest,string id)
        {
            contest.Winner_Id = id;
            if (ModelState.IsValid)
            {
                db.Entry(contest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contest);
        }

        public ActionResult Announcement()
        {
           List<Contest> li =db.Contests.Where(x => x.Winner_Id != null).ToList();
            List<string> cName = new List<string>();
            List<string> winnerName = new List<string>();
           foreach(var item in li)
            {
                cName.Add(item.Name);
                winnerName.Add(db.AspNetUsers.Where(x => x.Id == item.Winner_Id).Select(x => x.UserName).SingleOrDefault());
            }
            ViewBag.CName = cName;
            ViewBag.WName = winnerName;
            return View();
        }

            public ActionResult Announced(int id)
        {
            String p = db.Participants.Where(x => x.Id == id).Select(x => x.User_Id).SingleOrDefault();
            Contest c = db.Contests.Where(x => x.Id == id).SingleOrDefault();
            c.Winner_Id = p;
            if (ModelState.IsValid)
            {
                db.Entry(c).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Announcement");
            }
            return View("Announcement");
        }

        // GET: Contests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.Contests.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // POST: Contests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contest contest = db.Contests.Find(id);
            db.Contests.Remove(contest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public void ChangeStatus()
        {
            var now = DateTime.Now.Date;
            List<Contest> li=db.Contests.ToList();
            foreach(var item in li)
            {
                if(item.Ending_Date<=now)
                {
                    item.Status = "inactive";
                    db.SaveChanges();
                }
            }
        }
        

    }
}

JamesThew/model/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using model;

namespace model.Controllers
{
    public class RecipesController : Controller
    {
        private DefaultConnectionEntities db = new DefaultConnectionEntities();

        // GET: Recipes
        public ActionResult Index()
        {
             var recipes = db.Recipes.Include(r => r.AspNetRole).Include(r => r.AspNetUser);
            return View(recipes.ToList());
        }

        // GET: Recipes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }
        
        // GET: Recipes/Create
        public ActionResult Create(HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {

                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Content/images/" + ImageName);

                    // save image in folder
                    file.SaveAs(physicalPath);

                }

                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name");
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Recipe_Id,Recipe_Name,Description,Ingredients,Label,Posted_by")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                

                db.Recipes.Add(recipe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name", recipe.Label);
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email", recipe.Posted_by);
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name", recipe.Label);
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email", recipe.Posted_by);
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Recipe_Id,Recipe_Name,Description,Ingredients,Label,Posted_by")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name", recipe.Label);
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email", recipe.Posted_by);
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipe = db.Recipes.Find(id);
            db.Recipes.Remove(recipe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Feedback()
        {
            return PartialView("_Feedback");
        }

        public PartialViewResult _Feedback()
        {
            //Feedback_Recipe fr = new Feedback_Recipe();
            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name");
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email");

            return PartialView();
        }

        //public PartialViewResult _Comment()
        //{


        //    return PartialView();
        //}

    }
}

JamesThew/model/Controllers/TipsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using model;

namespace model.Controllers
{
    public class TipsController : Controller
    {
        private DefaultConnectionEntities db = new DefaultConnectionEntities();

        // GET: Tips
        public ActionResult Index()
        {
            var tips = db.Tips.Include(t => t.AspNetRole).Include(t => t.AspNetUser);
            return View(tips.ToList());
        }

        // GET: Tips/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            return View(tip);
        }

        // GET: Tips/Create
        public ActionResult Create()
        {
            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name");
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Tips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Tips_Id,Tips_Name,Description,Label,Posted_by")] Tip tip)
        {
            if (ModelState.IsValid)
            {
                db.Tips.Add(tip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name", tip.Label);
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email", tip.Posted_by);
            return View(tip);
        }

        // GET: Tips/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name", tip.Label);
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email", tip.Posted_by);
            return View(tip);
        }

        // POST: Tips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Tips_Id,Tips_Name,Description,Label,Posted_by")] Tip tip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Label = new SelectList(db.AspNetRoles, "Id", "Name", tip.Label);
            ViewBag.Posted_by = new SelectList(db.AspNetUsers, "Id", "Email", tip.Posted_by);
            return View(tip);
        }

        // GET: Tips/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            return View(tip);
        }

        // POST: Tips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tip tip = db.Tips.Find(id);
            db.Tips.Remove(tip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JamesThew/model/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#dashboard").show();
        });



    </script>

    <!-- Basic -->

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">
    <!-- Site Metas -->
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--===============================================================================================-->
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Styling/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Styling/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Styling/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Styling/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Styling/css/main.css">
    <!--===============================================================================================-->
    <!-- Site Icons -->
    <link rel="shortcut icon" href="~/Content/images/jamesthewicon1.png" type="image/x-icon" />
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="~/Content/css/style.css">
    
    
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="~/Content/css/responsive.css">
    <!-- color -->
    <link id="changeable-colors" rel="stylesheet" href="~/Content/css/colors/orange.css" />
    <!-- Modernizer -->
    <script src="~/Content/js/modernizer.js"></script>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body style="background-image: url('../../Content/images/Bg.png');margin-top:-50px">

    <div id="loader">
        <div id="status"></div>
    </div>
    <div id="site-header">
        <header id="header" class="header-block-top">
            <div class="container">
                <div class="row">
                    <div class="main-menu">
                        <!-- navbar -->
                        <nav class="navbar navbar-default" id="mainNav">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <div class="logo" style="margin-left:-100px">
                                    <!-- nav logo -->

                                    
                                    <a class="navbar-brand js-scroll-trigger logo-header" href="@Url.Action("Index","Home")">
                                        <img src="~/Content/images/jamesThew11.png" height="90" width="150" alt="">
                                    </a>
                                </div>
                            </div>
                            <div id="navbar" class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">

                                    <li class="active"><a href="@Url.Action("Index","Home")">Home</a></li>
                                    <li><a href="@Url.Action("Index","Recipes")">Recipes</a></li>
                                    <li><a href="@Url.Action("Index","Tips")">Tips</a></li>
                                    <li><a href="@Url.Action("Index","Contests")">Contests</a></li>
                                    <li><a href="@Url.Action("Announcement","Contests")">Announcements</a></li>
                                    @if (!User.IsInRole("admin"))
                                    {
                                    <li><a href="@Url.Action("Create", "Feedbacks")">FeedBack</a></li>
                                    <li><a href="@Url.Action("FAQ", "Home")">FAQ's</a></li>
                                    }
                                    else
                                    { <li><a href="@Url.Action("Index", "Feedbacks")">FeedBack</a></li>}
                                </ul>
                                @Html.Partial("_LoginPartial")

                                

                            </div>
                            <!-- end nav-collapse -->
                        </nav>
                        <!-- end navbar -->
                    </div>


                </div>
                <!-- end row -->
            </div>
            <!-- end container-fluid -->
        </header>
        <!-- end header -->

    </div>
    <!-- end site-header -->


    @RenderBody()

    <div id="footer" class="footer-main">

        <div class="footer-box pad-top-70">

            <div class="container">

                <div class="row">

                    <div class="footer-in-main">

                        <div class="footer-logo">
                            <div class="text-center">
                                <!-- footer logo -->
                                <img src="~/Content/images/jamesthew.png" alt="" height="200" width="250" />
                            </div>
                        </div>
                        <br />
                        <br />
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                            <div class="footer-box-a">
                                <h3>About Us</h3>
                                <p>James Thew is one of the famous cook working in one of the five star hotels in the city.</p>
                                <ul class="socials-box footer-socials pull-left">
                                    <li>
                                        <a href="https://www.facebook.com">
                                            <div class="social-circle-border"><i class="fa  fa-facebook"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.twitter.com">
                                            <div class="social-circle-border"><i class="fa fa-twitter"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.plus.google.com">
                                            <div class="social-circle-border"><i class="fa fa-google-plus"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.pinterest.com">
                                            <div class="social-circle-border"><i class="fa fa-pinterest"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.linkedin.com">
                                            <div class="social-circle-border"><i class="fa fa-linkedin"></i></div>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- end footer-box-a -->
                        </div>
                        <!-- end col -->
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">




                            <!-- end footer-box-b -->
                        </div>
                        <!-- end col -->
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                            <div class="footer-box-c">
                                <h3>Contact Us</h3>
                                <p>
                                    <i class="fa fa-map-signs" aria-hidden="true"></i>
                                    <span>6 E Esplanade, St Albans VIC 3021, Australia</span>
                                </p>
                                <p>
                                    <i class="fa fa-mobile" aria-hidden="true"></i>
                                    <span>
                                        +91 80005 89080
                                    </span>
                                </p>
                                <p>
                                    <i class="fa fa-envelope" aria-hidden="true"></i>
                                    <span>support@JamesThew.com</span>
                                </p>
                            </div>
                            <!-- end footer-box-c -->
                        </div>
                        <!-- end col -->
                    </div>
                    <!-- end footer-in-main -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
            <div id="copyright" class="copyright-main">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <h6 class="copy-title"> Copyright &copy; 2019 <a href="@Url.Action("Index","Home")" target="_blank">James Thew</a> </h6>
                        </div>
                    </div>
                    <!-- end row -->
                </div>
                <!-- end container -->
            </div>
            <!-- end copyright-main -->
        </div>
        <!-- end footer-box -->
    </div>
    <!-- end footer-main -->
    <a href="#" class="scrollup" style="display: none;">Scroll</a>

    <!-- ALL JS FILES -->
    <script src="~/Content/js/all.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- ALL PLUGINS -->
    <script src="~/Content/js/custom.js"></script>
    <script src="~/Content/js/modernizer.js"></script>








    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!--===============================================================================================-->
    <script src="~/Content/Styling/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/Styling/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/Styling/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/Styling/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/Styling/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>

    <!--===============================================================================================-->
    <script src="js/main.js"></script>

</body>

</html>